// import { lazy } from 'react';
export { default as About } from './About';
export { default as Banner } from './Banner';
export { default as BrandPage } from './Brand';
export { default as Category } from './Category';
export { default as Discount } from './Discount';
export { default as DashBoard } from './Home';
export { default as FAQ } from './FAQs';
export { default as Feature } from './Feature';
export { ImportPage, OrderPage } from './Receipt';
export { default as Label } from './Label';
export { default as Login } from './Login';
export { default as Notification } from './Notification';
export { default as Pricing } from './Pricing';
export { default as ProductPage } from './Product';
export { default as ProductExperiences } from './ProductExperiences';
export { default as Profile } from './Profile';
export { default as ProductStatistic } from './Statistic/Products';
export { default as ProfitStatistic } from './Statistic/Profits';
export { default as SystemStatistic } from './Statistic/System';
export { default as Setting } from './Setting';
export { default as Role } from './Role';
export { default as User } from './User';
export { default as ResetPassword } from './ResetPassword';
